
export const authConstants = {
    USER_SIGNUP_REQUEST: 'USER_SIGNUP_REQUEST',
    USER_SIGNUP_SUCCESS: 'USER_SIGNUP_SUCCESS',
    USER_SIGNUP_FAILURE: 'USER_SIGNUP_FAILURE',

    USER_LOGIN_REQUEST: 'USER_LOGIN_REQUEST',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAILURE: 'USER_LOGIN_FAILURE',

    USER_LOGOUT_REQUEST: 'USER_LOGOUT_REQUEST',
    USER_LOGOUT_SUCCESS: 'USER_LOGOUT_SUCCESS',
    USER_LOGOUT_FAILURE: 'USER_LOGOUT_FAILURE',
}

export const medicationConstants = {
    ADD_MEDICATION_REQUEST: 'ADD_MEDICATION_REQUEST',
    ADD_MEDICATION_SUCCESS: 'ADD_MEDICATION_SUCCESS',
    ADD_MEDICATION_FAILURE: 'ADD_MEDICATION_FAILURE',

    GET_MEDICATIONS_REQUEST: 'GET_MEDICATIONS_REQUEST',
    GET_MEDICATIONS_SUCCESS: 'GET_MEDICATIONS_SUCCESS',
    GET_MEDICATIONS_FAILURE: 'GET_MEDICATIONS_FAILURE',

    EDIT_MEDICATION_REQUEST: 'EDIT_MEDICATION_REQUEST',
    EDIT_MEDICATION_SUCCESS: 'EDIT_MEDICATION_SUCCESS',
    EDIT_MEDICATION_FAILURE: 'EDIT_MEDICATION_FAILURE',

    DELETE_MEDICATIONS_REQUEST: 'DELETE_MEDICATIONS_REQUEST',
    DELETE_MEDICATIONS_SUCCESS: 'DELETE_MEDICATIONS_SUCCESS',
    DELETE_MEDICATIONS_FAILURE: 'DELETE_MEDICATIONS_FAILURE',
}